#!/bin/bash
# Creates "TuneBridge.app" in /Applications using a tiny C launcher binary.
#
# The C binary (compiled from launcher.c) is a proper Mach-O — macOS fires
# the TCC Documents prompt on first launch, then remembers the permission.
# The binary execs into CLT Python, which opens tunebridge_gui.py (in
# ~/Documents). Unlike PyInstaller, there's no complex bundle structure to
# confuse codesign.
#
# Run once after install: bash create_app.sh

set -e

APP_NAME="TuneBridge"
APP_PATH="/Applications/${APP_NAME}.app"
PROJECT_DIR="$(cd "$(dirname "$0")" && pwd)"
VENV_PYTHON="${PROJECT_DIR}/venv/bin/python"
CUSTOM_ICON="${PROJECT_DIR}/static/TuneBridge.icns"

# ── Find CLT Python ───────────────────────────────────────────────────────────
CLT_PYTHON=""
for candidate in \
    "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/bin/python3" \
    "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.11/bin/python3" \
    "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.12/bin/python3"; do
    if [ -x "$candidate" ]; then
        CLT_PYTHON="$candidate"
        break
    fi
done

if [ -z "$CLT_PYTHON" ]; then
    echo "ERROR: CLT Python not found. Install Xcode Command Line Tools:"
    echo "  xcode-select --install"
    exit 1
fi
CLT_PYVER="$("$CLT_PYTHON" -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')"
PYPATH="${PROJECT_DIR}/venv/lib/python${CLT_PYVER}/site-packages"

if [ ! -d "$PYPATH" ]; then
    echo "ERROR: venv site-packages not found at: $PYPATH"
    echo "  Run install.sh first, or ensure your venv uses Python ${CLT_PYVER}."
    exit 1
fi

echo "Building ${APP_NAME}.app (C launcher + pywebview / WKWebView)..."
echo "  CLT Python: $CLT_PYTHON ($CLT_PYVER)"
echo "  PYTHONPATH: $PYPATH"
echo "  PROJECT_DIR: $PROJECT_DIR"

# ── Remove stale versions ─────────────────────────────────────────────────────
for OLD in "/Applications/Music Manager.app" "/Applications/TuneBridge.app"; do
    [ -d "$OLD" ] && { echo "  Removing ${OLD}..."; rm -rf "$OLD"; }
done

# ── Ensure pywebview is installed in venv ────────────────────────────────────
if ! "$VENV_PYTHON" -c "import webview" 2>/dev/null; then
    echo "  Installing pywebview..."
    "${PROJECT_DIR}/venv/bin/pip" install pywebview --quiet
fi

# ── Generate and compile C launcher ──────────────────────────────────────────
# Use Python to write the .c file so paths with spaces are handled safely.
LAUNCHER_C="/tmp/tunebridge_launcher.c"
"$VENV_PYTHON" - "$LAUNCHER_C" "$PROJECT_DIR" "$CLT_PYTHON" "$PYPATH" <<'PYEOF'
import sys
out, project, python, pypath = sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4]

# Escape backslashes and double-quotes for C string literals
def esc(s):
    return s.replace('\\', '\\\\').replace('"', '\\"')

src = f'''\
/*
 * TuneBridge launcher — auto-generated by create_app.sh
 * Sets up Python environment and hands off to tunebridge_gui.py.
 */
#include <stdlib.h>
#include <unistd.h>

#define PROJECT "{esc(project)}"
#define PYTHON  "{esc(python)}"
#define SCRIPT  PROJECT "/tunebridge_gui.py"
#define PYPATH  "{esc(pypath)}"

int main(void) {{
    setenv("PYTHONPATH", PYPATH, 1);
    setenv("TUNEBRIDGE_PROJECT_DIR", PROJECT, 1);
    char *args[] = {{ PYTHON, SCRIPT, NULL }};
    execv(PYTHON, args);
    return 1; /* execv only returns on failure */
}}
'''
with open(out, 'w') as f:
    f.write(src)
print(f"  Generated {out}")
PYEOF

LAUNCHER_BIN="/tmp/TuneBridgeLauncher"
clang -o "$LAUNCHER_BIN" "$LAUNCHER_C" && echo "  Compiled launcher binary (Mach-O)"

# ── Build .app bundle ─────────────────────────────────────────────────────────
CONTENTS="${APP_PATH}/Contents"
MACOS="${CONTENTS}/MacOS"
RESOURCES="${CONTENTS}/Resources"

mkdir -p "$MACOS" "$RESOURCES"

# Executable
cp "$LAUNCHER_BIN" "${MACOS}/${APP_NAME}"
chmod +x "${MACOS}/${APP_NAME}"

# Icon
if [ -f "$CUSTOM_ICON" ]; then
    cp "$CUSTOM_ICON" "${RESOURCES}/TuneBridge.icns"
    ICON_KEY="<key>CFBundleIconFile</key><string>TuneBridge</string>"
else
    ICON_KEY=""
fi

# Info.plist — written via Python for correct escaping
"$VENV_PYTHON" - "$CONTENTS/Info.plist" "$PROJECT_DIR" "$ICON_KEY" <<'PYEOF'
import plistlib, sys
plist_path, project_dir, icon_key = sys.argv[1], sys.argv[2], sys.argv[3]

plist = {
    'CFBundleName': 'TuneBridge',
    'CFBundleDisplayName': 'TuneBridge',
    'CFBundleIdentifier': 'com.tunebridge.app',
    'CFBundleVersion': '1.0',
    'CFBundleShortVersionString': '1.0',
    'CFBundleExecutable': 'TuneBridge',
    'CFBundlePackageType': 'APPL',
    'CFBundleSignature': '????',
    'NSHighResolutionCapable': True,
    'LSMinimumSystemVersion': '12.0',
    'NSAppTransportSecurity': {'NSAllowsLocalNetworking': True},
    # Request Documents access — required for TCC prompt to fire on first launch
    'NSDocumentsFolderUsageDescription':
        'TuneBridge needs access to your Documents folder to reach your music library and playlists.',
    'LSEnvironment': {
        'TUNEBRIDGE_PROJECT_DIR': project_dir,
    },
}
if icon_key:
    plist['CFBundleIconFile'] = 'TuneBridge'

with open(plist_path, 'wb') as f:
    plistlib.dump(plist, f)
print(f"  Wrote Info.plist (NSDocumentsFolderUsageDescription included)")
PYEOF

# ── Ad-hoc sign ──────────────────────────────────────────────────────────────
# Single binary + Info.plist only — no complex bundle structure to confuse codesign.
codesign --force --sign - "$APP_PATH" 2>/dev/null && echo "  Ad-hoc signed" || \
    echo "  WARNING: codesign failed — app may not launch. Run: codesign --force --sign - \"$APP_PATH\""

# ── Clear quarantine ──────────────────────────────────────────────────────────
xattr -cr "$APP_PATH" 2>/dev/null || true

# ── Clean up ──────────────────────────────────────────────────────────────────
rm -f "$LAUNCHER_C" "$LAUNCHER_BIN"

echo ""
echo "  ✓ ${APP_NAME}.app installed to /Applications"
echo ""
echo "  FIRST LAUNCH: macOS will ask for access to ~/Documents."
echo "  Click 'Allow' — this is needed to reach your music library."
echo "  (This prompt only appears once.)"
echo ""
echo "  How it works:"
echo "    • Native WKWebView window — no Safari"
echo "    • Cmd+Tab shows 'TuneBridge'"
echo "    • Closing the window stops the server"
echo ""
echo "  To run from Terminal instead:"
echo "    cd \"${PROJECT_DIR}\" && source venv/bin/activate && python tunebridge_gui.py"
echo ""
